### ISSUE TITLE
King's Court on Pillage freezes game and Tournament does not give a Duchy. 

### ISSUE THREAD

**Issue by ziolek666** [jcbantuelle/dominion-meteor#14]
Hi again. This time the game froze after playing King's Court on a Pillage (on third time) also trashing the wrong card (King's Court instead of Pillage). 

The log:

```
Exception in callback of async function: TypeError: Cannot read property 'types' of undefined
   at app/game/server/view_objects/card_view.js:16:33
```

Attached screenshot form the game: 
<img width="575" alt="screen shot 2016-08-23 at 02 23 35" src="https://cloud.githubusercontent.com/assets/8878195/17912561/a858bff4-6994-11e6-9a10-b5b17873a757.png">

Again thanks for the great work! 

P.S. We also found a minor bug: Tournament does not give a Duchy after Prizes are depleted.

**Comment by jcbantuelle** [comment]
I actually fixed this bug earlier today, in https://github.com/jcbantuelle/dominion-meteor/commit/bd874dcfd1b8227abb5fd22f7d2566f5fd686908. You just need to pull in the latest version. I'm going to go ahead and close this issue, but I'll add the Duchy option to Tournament soon.

**Comment by jcbantuelle** [comment]
I just pushed a fix for the Tournament issue in https://github.com/jcbantuelle/dominion-meteor/commit/cc53ce5fe2d3defbccca8f04addad1e26af9980b. There was a second bug where it wasn't putting the gained card on top of your deck, which is also corrected here.

**Comment by ziolek666** [comment]
Great, Thanks!
