### ISSUE TITLE
Routing problem on Game History page

### ISSUE THREAD

**Issue by ziolek666** [jcbantuelle/dominion-meteor#15]
Hi! 

I've noticed that there is probably a routing problem with Game History page. When I try to go to Games History page form any other page it's not displayed correctly unless I reload the page before going to Games History or reload the Games History page itself. Tested on Chrome and Firefox. All I've got form the console is:

```
Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?
```

After reloading the console is clear. Attached GIF:

![gh_bug](https://cloud.githubusercontent.com/assets/8878195/17953969/1257af4e-6a78-11e6-9c47-871f320202a1.gif)

Thanks again for your work on the game!

**Comment by jcbantuelle** [comment]
Thanks for the report. I've noticed this behavior as well, but have no earthly idea what is causing it.  I tried looking into it a little bit but wasn't coming up with any good leads. As you noticed, refreshing resolves the problem, which is just what I've been doing. I'm not sure when I'll get around to looking into it again, but if you wanted to investigate please feel free!
