### ISSUE TITLE
Duplicate does not let you choose "No"

### ISSUE THREAD

**Issue by ziolek666** [jcbantuelle/dominion-meteor#17]
Hi again.

 I have another issue with Duplicate. 

When you have a Duplicate card on your tavern mat and you buy a card it does not let you choose "No". The game will not continue unless "Yes" is chosen.

Cheers!

**Comment by jcbantuelle** [comment]
Thanks for the report. This has been fixed and pushed in eef6e4aab7532e21e55b85ce0ed2bdb679161f31
