### ISSUE TITLE
Rogue shows empty checkboxes

### ISSUE THREAD

**Issue by stasm** [jcbantuelle/dominion-meteor#20]
When playing _Rogue_ and there are cards in the trash costing between $3 and $6, the UI for picking one of them to gain has checkboxes without labels:

![screen shot 2016-09-27 at 21 12 49](https://cloud.githubusercontent.com/assets/265818/18888171/85b39e78-84f7-11e6-91f1-4cfc9c28049e.png)

**Comment by jcbantuelle** [comment]
Thanks for the report! Fixed.
