### ISSUE TITLE
Implementing NOCTURNE

### ISSUE THREAD

**Issue by michalbe** [jcbantuelle/dominion-meteor#21]
Hello,
Last year the new expansion set was released - [Nocturne](http://wiki.dominionstrategy.com/index.php/Nocturne). Do you plan to implement it?

**Comment by jcbantuelle** [comment]
Thanks for bringing this to my attention. I haven't kept up with the releases of this game and didn't know a new expansion had come out. It also looks like the Base and Intrigue sets got 2nd editions with some rule errata and a few card removals/additions.

I'll look at adding all of this to the app in the next month or two.

**Comment by michalbe** [comment]
Really looking forward to that!

**Comment by jcbantuelle** [comment]
I know it's not the question you asked, but when I started looking at the game resources for Nocture I realized that a Second Edition had been released for almost all of the expansions, with actual card additions/deletions for Base and Intrigue and some rule errata

I went ahead and update all of the new card rules, added the 14 new cards, and put in a toggle to choose between first and second editions, with second edition being the default https://github.com/jcbantuelle/dominion-meteor/pull/23

Now that this is done, I'm going to start working on Nocture, but figured I'd let you know about these updates in the meantime.

**Comment by michalbe** [comment]
Great, thanks!

**Comment by jcbantuelle** [comment]
I've finished implementing Nocturne, and merged it in with https://github.com/jcbantuelle/dominion-meteor/pull/25.

There were a lot of clunky new mechanics introduced, so I wouldn't be surprised if there are bugs that emerge from strange card interactions, or just from me misreading card rules. I haven't had a chance to play test at all against another opponent yet, just the local testing to make sure cards have basic functionality.

Please feel free to open issues for any bugs you come across while testing.
