### ISSUE TITLE
Storeroom throws exception when played

### ISSUE THREAD

**Issue by cgrinds** [jcbantuelle/dominion-meteor#43]
When playing storeroom the following exception happens because option is not defined.

Exception in callback of async function: ReferenceError: option is not defined
    at app/cards/dark_ages/storeroom.js:44:11
    at arrayEach
    at Function.forEach
    at Storeroom.play
    at CardPlayer.play_card
    at app/game/server/services/card_player.js:30:32
    at baseTimes
    at Function.times
    at CardPlayer.play
    at app/game/server/game.js:22:25
    at runWithEnvironment
    at packages/meteor.js:1299:14

**Comment by jcbantuelle** [comment]
Thanks for catching this issue. I've tested and pushed a fix to master, 5149485
