### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cgrinds** [jcbantuelle/dominion-meteor#45]
https://github.com/jcbantuelle/dominion/blob/cf2f2f92683891d0af43b571ed41b25d3a745f2a/app/cards/nocturne/will_o_wisp.js#L24

Change thier to their

Same in https://github.com/jcbantuelle/dominion/blob/cf2f2f92683891d0af43b571ed41b25d3a745f2a/app/cards/renaissance/projects/city_gate.js#L30

**Comment by jcbantuelle** [comment]
Good catch, please feel free to open a PR to correct it

**Comment by jcbantuelle** [comment]
Fixed by https://github.com/jcbantuelle/dominion/pull/46, thanks!
